# Generated by Django 5.1.7 on 2025-03-20 17:54

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Campaign = apps.get_model('campaigns', 'Campaign')
    for campaign in Campaign.objects.all():
        if not campaign.slug:
            base_slug = slugify(campaign.title)
            slug = base_slug
            counter = 1
            # Handle duplicate slugs
            while Campaign.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            campaign.slug = slug
            campaign.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0002_campaign_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_func),
    ]