# Generated by Django 5.1.7 on 2025-03-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_populate_campaign_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
