# Generated by Django 5.1.7 on 2025-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='icon',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
    ]
