# Generated by Django 5.1.7 on 2025-03-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rarity', models.CharField(blank=True, choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary'), ('ARTIFACT', 'Artifact'), ('VARIES', 'Varies')], max_length=50)),
                ('is_magic', models.BooleanField()),
                ('requires_attunement', models.BooleanField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
